version: '3'
services:
  microsoft-rewards-script:
    build: .
    container_name: netsky
    environment:
      - TZ=America/Toronto # Change to your local timezone
      - NODE_ENV=production
      - HEADLESS=true # Do not change
      ### Customize your run schedule, default 5:00 am and 11:00 am, use crontab.guru for formatting
      - CRON_START_TIME=0 5,11 * * *
      ### Run on start, set to false to only run the script per the cron schedule
      - RUN_ON_START=true 
      - DATA_PATH=${DATA_PATH:-./} # Set default to ./ if not provided
    volumes:
      ### Use the environment variable for the file paths
      - ${DATA_PATH}/accounts.json:/usr/src/microsoft-rewards-script/dist/accounts.json
      - ${DATA_PATH}/config.json:/usr/src/microsoft-rewards-script/dist/config.json
      - ${DATA_PATH}/sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions # Optional, saves your login session
    deploy:
      resources:
        limits:
          memory: 2048M    
    restart: unless-stopped
